### ISSUE TITLE
Crashed when installing

### ISSUE THREAD

**Issue by davidmartinrius** [BrokenSource/BrokenSource#2]
Hi!
How are you doing? I got this error in a fresh installation:

156 BrokenEnum /mydir/BrokenSource/Broken/BrokenEnum/BrokenEnum.py

> def get(cls, value: Union[str, Enum, Any], *, lowercase: bool=True) -> Optional[Self]:
     
NameError:
name 'Self' is not defined
Failed to clone one or many essential or not public submodules

I followed the instructions. Is there any other requirement before ?
I tried both installation methods:
git clone https://github.com/BrokenSource/BrokenSource
python ./BrokenSource/brakeit.py
AND
curl -sSL https://github.com/BrokenSource/BrokenSource/raw/Master/brakeit.py | python3 -

I am using an Ubuntu 22 and a python3.10

Thank you!

David Martin Rius

**Comment by davidmartinrius** [comment]
ok, I realized that it is needed python11 to make it work. It would be great if specified in the documentation.

**Comment by Tremeschin** [comment]
Yup, Python version

I never really tested the code on older py versions. Good catch here!

I'll branch the code properly to import / define the `Self`

**Comment by Tremeschin** [comment]
> I'll branch the code properly to import / define the `Self`

Just commited the fix in 5dabb85

I installed Python 3.10 locally with `pyenv install 3.10`, initialized it with `eval "$(pyenv init -)"`, ran the `brakeit.py` script, no issues with it and running other projects also worked

Trivia: This variable is only used as type hint, as proposed on [PEP 673](https://peps.python.org/pep-0673), removing it makes no difference, just poorer, well, function type hinting

You can revert to Python 3.10 if that's the current stable/default on Ubuntu 22, just remember to `git pull` !  :)

**Comment by davidmartinrius** [comment]
Thank you!!
