### ISSUE TITLE
(BUG) Possible Spinner bug after last merge

### ISSUE THREAD

**Issue by Soranokuni** [BrokenSource/BrokenSource#4]
Hi again!
It seems that the current upstream has some problems on linux, tested on multiple distros(fedora, pop-os(debian/ubuntu).
I think it has to do with the recent spinner updates, there's the following terminal output:
![Screenshot from 2024-03-26 20-21-17](https://github.com/BrokenSource/BrokenSource/assets/1796296/8d3d1cec-6d7b-4afd-b675-bd83ef99ca92)

**Comment by Soranokuni** [comment]
False alarm, I am sorry.

There is a bug but only on Python3.10 which previously was compatible, using pyenv and setting 3.11.8 works.
Python 3.10 and Python 3.12 panic though.

**Comment by Tremeschin** [comment]
I forgot about this one

I was star importing and manually defining Self for Python < 3.11 in a centralized file, just recently resolved them/made explicit to absolute paths imports and don't have this small fix anymore, it's a couple commits older than the spinner

I'm moving tooling to Rye, might take a day or two for the commit to implement and test, but everyone will be on the same Python version there, and will also define it on a common file probably just for compatibility sake for 3.10 minimum version

**Comment by Tremeschin** [comment]
I've successfully ran the code on Python 3.10 managed now by [`rye`](https://rye-up.com) after fix on commit [7b9f33c](https://github.com/BrokenSource/BrokenSource/commit/7b9f33c05767947e4efc685f304de7efc65c4485)

It's a monkey patch on the imported module `typing` itself, so changes propagate everywhere to define `Self=Any`

Reopen if you still have issues, though this would only happen if disabling auto managed python version on the new tooling and using system's one, or changing `.python-version` to `3.10` (what I did) but I could execute code there
