### ISSUE TITLE
SegFault when trying to run depthflow in MacBook M2

### ISSUE THREAD

**Issue by hucara** [BrokenSource/BrokenSource#5]
### Operating System

macOS 23 (Sonoma)

### Python Version

Python 3.11

### Runtime Enviroment

Source Code (Install Scripts or Manual)

### GPU Vendor (if applicable)

N/A

### Description

Segmentation fault when trying to run depthflow in Macbook M2

`❯ broken depthflow --help
│Broken    ├┤  79ms├┤INFO   │ ▸ Hey! Just type 'depthflow' to run the project with Rye, it's faster 😉
❯ depthflow
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                          │
│                              ██████████                       █████    █████      ███████████ ████                                                       │
│                             ░░███░░░░███                     ░░███    ░░███      ░░███░░░░░░█░░███                                                       │
│                              ░███   ░░███  ██████  ████████  ███████   ░███████   ░███   █ ░  ░███   ██████  █████ ███ █████                             │
│                              ░███    ░███ ███░░███░░███░░███░░░███░    ░███░░███  ░███████    ░███  ███░░███░░███ ░███░░███                              │
│                              ░███    ░███░███████  ░███ ░███  ░███     ░███ ░███  ░███░░░█    ░███ ░███ ░███ ░███ ░███ ░███                              │
│                              ░███    ███ ░███░░░   ░███ ░███  ░███ ███ ░███ ░███  ░███  ░     ░███ ░███ ░███ ░░███████████                               │
│                              ██████████  ░░██████  ░███████   ░░█████  ████ █████ █████       █████░░██████   ░░████░████                                │
│                             ░░░░░░░░░░    ░░░░░░   ░███░░░     ░░░░░  ░░░░ ░░░░░ ░░░░░       ░░░░░  ░░░░░░     ░░░░ ░░░░                                 │
│                                                    ░███                                                                                                  │
│                                                    █████                                                                                                 │
│                                                   ░░░░░                                                                                                  │
│                                                                                                                                                          │
╰─────────────────────────────────────────────────────── Made with ❤️ by BrokenSource, Python 3.11.8 ───────────────────────────────────────────────────────╯

│DepthFlow ├┤ 274ms├┤INFO   │ ▸ ( 1) DepthFlowScene     │ ▸ Module added to the Scene
│DepthFlow ├┤ 276ms├┤INFO   │ ▸ ( 1) DepthFlowScene     │ ▸ Creating Window and OpenGL Context
│DepthFlow ├┤ 276ms├┤INFO   │ ▸ ( 1) DepthFlowScene     │ ▸ • Backend:    glfw
│DepthFlow ├┤ 276ms├┤INFO   │ ▸ ( 1) DepthFlowScene     │ ▸ • Resolution: (1920, 1080)
│DepthFlow ├┤ 402ms├┤INFO   │ ▸ ( 1) DepthFlowScene     │ ▸ Adding default base Scene modules
│DepthFlow ├┤ 403ms├┤INFO   │ ▸ ( 2) ShaderFrametimer   │ ▸ Module added to the Scene
│DepthFlow ├┤ 403ms├┤INFO   │ ▸ ( 3) ShaderKeyboard     │ ▸ Module added to the Scene
│DepthFlow ├┤ 404ms├┤INFO   │ ▸ ( 4) ShaderCamera       │ ▸ Module added to the Scene
│DepthFlow ├┤ 404ms├┤INFO   │ ▸ ( 5) ShaderDynamics     │ ▸ Module added to the Scene
│DepthFlow ├┤ 404ms├┤INFO   │ ▸ ( 6) ShaderDynamics     │ ▸ Module added to the Scene
│DepthFlow ├┤ 405ms├┤INFO   │ ▸ ( 7) ShaderDynamics     │ ▸ Module added to the Scene
│DepthFlow ├┤ 405ms├┤INFO   │ ▸ ( 8) ShaderDynamics     │ ▸ Module added to the Scene
│DepthFlow ├┤ 405ms├┤INFO   │ ▸ ( 9) ShaderDynamics     │ ▸ Module added to the Scene
│DepthFlow ├┤ 405ms├┤INFO   │ ▸ (10) ShaderDynamics     │ ▸ Module added to the Scene
│DepthFlow ├┤ 406ms├┤INFO   │ ▸ (11) ShaderDynamics     │ ▸ Module added to the Scene
│DepthFlow ├┤ 406ms├┤INFO   │ ▸ (12) ShaderDynamics     │ ▸ Module added to the Scene
│DepthFlow ├┤ 406ms├┤INFO   │ ▸ ( 1) DepthFlowScene     │ ▸ Creating SSAA Implementation
│DepthFlow ├┤ 406ms├┤INFO   │ ▸ (13) ShaderObject       │ ▸ Module added to the Scene
│DepthFlow ├┤ 407ms├┤INFO   │ ▸ (14) ShaderTexture      │ ▸ Module added to the Scene
│DepthFlow ├┤ 410ms├┤INFO   │ ▸ (15) ShaderObject       │ ▸ Module added to the Scene
│DepthFlow ├┤ 410ms├┤INFO   │ ▸ (16) ShaderTexture      │ ▸ Module added to the Scene
│DepthFlow ├┤ 412ms├┤INFO   │ ▸ (17) ShaderTexture      │ ▸ Module added to the Scene
│DepthFlow ├┤ 413ms├┤INFO   │ ▸ (18) ShaderTexture      │ ▸ Module added to the Scene
│DepthFlow ├┤ 418ms├┤INFO   │ ▸ (13) ShaderObject       │ ▸ Compiling shaders
[1]    36199 segmentation fault  depthflow
`

### Reproducing the Issue (if applicable)

Installed following MacOs instructions from docs.
1. Rye was not found after first install try but managed to make it work after that.
2. /bin/bash -c "$(curl -sS https://brokensrc.dev/get.sh)"
3. depthflow

Had the same behaviour when installing from source.

**Comment by Tremeschin** [comment]
Hi friend, this is known, but I don't have the hardware to debug myself :(

related issues on the shader engine and depthflow repos:

- https://github.com/BrokenSource/ShaderFlow/issues/4

- https://github.com/BrokenSource/DepthFlow/issues/13
